version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    steps:
      - checkout

      # run tests!
      - run:
          name: run tests
          command: |
            ./test.sh
notify:
  webhooks:
    # A list of hook hashes, containing the URL field
    - url: $NGROK_URL
